on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs_on: ubuntu-latest

        steps:
            - name: Checkout the code
              uses: actions/checkout@v7.0.0

            - name: Test the code
              run: npm test
