services:
  server:
    build:
      context: .
    environment:
      PORT: ${PORT}
      DB_URL: ${DB_URL}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: npm run dev
    depends_on:
      - mongo
  
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
